import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Router from 'next/router';
import React from 'react';
import { AuthContextProvider } from '../src/contexts/authContext';
import { ThemeContextProvider } from '../src/contexts/themeContext';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<AuthContextProvider>
				<ThemeContextProvider>
					<React.StrictMode>{/* <App /> */}</React.StrictMode>
				</ThemeContextProvider>
			</AuthContextProvider>
		</div>
	);
};

export default Home;
